dist: xenial

language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django22 

env:
  - DJANGOVER=django22

install:
  - pip install tox
  - pip install pytest

script:
  - pytest
